sudo: required
dist: trusty
language: c

matrix:
  include:
    - env: HOST=i686-w64-mingw32 TARGET=i686-w64-mingw32 
    - env: HOST=x86_64-w64-mingw32 TARGET=x86_64-w64-mingw32 

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y git mingw-w64 binutils-mingw-w64 automake autoconf libudev-dev libtool texinfo texlive;
  - export CC=$HOST-gcc
  - export CXX=$HOST-g++
  - "$CC -v"
  - "$CXX -v"
  - make --version
  - uname -a

before_script:
  - chmod +x build.sh clean.sh hidapi.build.sh libusb-compat-0.1.build.sh libusb.build.sh openocd.build.sh

script:
  - ./build.sh
