language: c

matrix:
  include:
    - env: TARGET=win WIN_TOOL=i686-w64-mingw32
    - env: TARGET=win WIN_TOOL=x86_64-w64-mingw32

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y git mingw-w64 binutils-mingw-w64 automake autoconf libudev-dev libtool texinfo texlive;
  - x86_64-w64-mingw32-gcc -v
  - i686-w64-mingw32-gcc -v
  - make --version
  - uname -a

before_script:
  - chmod +x build.sh clean.sh hidapi.build.sh libusb-compat-0.1.build.sh libusb.build.sh openocd.build.sh

script:
  - ./build.sh
